// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppBookingBoat.Repository;

#nullable disable

namespace WebAppBookingBoat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410235011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Nhân viên",
                            NormalizedName = "NHÂN VIÊN"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Khách hàng",
                            NormalizedName = "KHÁCH HÀNG"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "6e30006e-b30f-47b9-9e33-4a02d89d5b57",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "4248b3d7-0bbf-4475-b55b-8d5743802619",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6e30006e-b30f-47b9-9e33-4a02d89d5b57",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf2d361f-7834-40a4-974a-5beb4c76e4d8",
                            Email = "admin@booking.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BOOKING.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJmlTaxRUDYIfOtgRzTThkt45SYXAeF1nu0FQxj3Awad3B334FUyeP0uz4+9azA3AQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c919b018-4c56-4f45-8f71-302ab6a74671",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "4248b3d7-0bbf-4475-b55b-8d5743802619",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6a9b39a-6814-4973-ba12-0d73f4dab63f",
                            Email = "nhanvien1@booking.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NHANVIEN1@BOOKING.COM",
                            NormalizedUserName = "NHANVIEN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEJIjGlaG+sxN+9xPn4OimUe2mXr0BHeD2wb6kL0wwG135fd05YxAdKeQUKSs+r01ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e48ffae-581b-4755-92bd-87ebd5d55ac7",
                            TwoFactorEnabled = false,
                            UserName = "nhanvien1"
                        },
                        new
                        {
                            Id = "2824b0d2-08c9-4394-9f5e-8662b26699a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1f2390e-f80f-4dc0-9f68-b9dbdf8cc46f",
                            Email = "khachhang1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHACHHANG1@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG1",
                            PasswordHash = "AQAAAAIAAYagAAAAEAHWSTNzWFnuVVilZxTyUFksp8wHmsE4vzR+WvkMZ2SMYKkhIdoS/FaWglRFs5iodg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "336dce13-e0fc-4091-832c-aa723602c98c",
                            TwoFactorEnabled = false,
                            UserName = "khachhang1"
                        },
                        new
                        {
                            Id = "483851fa-b8a2-45f9-b583-67e81748cf6f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "490f4fe0-bd7e-496b-a9f8-939b802c9a5a",
                            Email = "khachhang2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHACHHANG2@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG2",
                            PasswordHash = "AQAAAAIAAYagAAAAEHRR3EKK1a3pq2dkoKbcF3gUWpCQAGk0A/2klcEuoWkGBgi91rQuMLlhOZ76ljdBTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9b3e199-9232-4ec8-885a-55eec6ec9432",
                            TwoFactorEnabled = false,
                            UserName = "khachhang2"
                        },
                        new
                        {
                            Id = "2b780c3e-a915-43de-aeff-3a827b66fb41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "088a539d-eab6-4170-88e7-d0719b7f7e0f",
                            Email = "testuser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER@GMAIL.COM",
                            NormalizedUserName = "TESTUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAENxo/jYopsrQKeZC3LUKtGjcMb9+FqJIdLOwqNa3H7h74UQ2KvAEygH/DM4d051Q5w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69cd8b9a-d079-4de8-9c7c-5305068d2c63",
                            TwoFactorEnabled = false,
                            UserName = "testuser"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("LichTrinhMaLichTrinh")
                        .HasColumnType("int");

                    b.Property<int>("MaVe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("LichTrinhMaLichTrinh");

                    b.HasIndex("MaVe")
                        .IsUnique();

                    b.ToTable("DanhGia", t =>
                        {
                            t.HasCheckConstraint("CK_DG_SoSao", "[SoSao] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_DG_TrangThai", "[TrangThai] IN (N'Chờ duyệt', N'Đã hiển thị', N'Đã ẩn')");
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("LoaiGhe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaTau")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaTau", "TenGhe")
                        .IsUnique();

                    b.ToTable("Ghe", t =>
                        {
                            t.HasCheckConstraint("CK_Ghe_LoaiGhe", "[LoaiGhe] IN (N'Thường', N'VIP')");
                        });

                    b.HasData(
                        new
                        {
                            MaGhe = 1,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 2,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 3,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 4,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 5,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 6,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 7,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 8,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 9,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 10,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 11,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 12,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 13,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 14,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 15,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 16,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 17,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 18,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 19,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 20,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-20"
                        },
                        new
                        {
                            MaGhe = 21,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 22,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 23,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 24,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 25,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 26,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 27,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 28,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 29,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 30,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 31,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 32,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 33,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 34,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 35,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 36,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 37,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 38,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 39,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 40,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-20"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<string>("MaKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongVe")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TamTinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKM");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_HD_SoLuong", "[SoLuongVe] > 0");

                            t.HasCheckConstraint("CK_HD_Tien", "[TamTinh] >= 0 AND [SoTienGiam] >= 0 AND [TongTien] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            MaHoaDon = 1,
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 11, 6, 50, 10, 25, DateTimeKind.Local).AddTicks(2867),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 2,
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 11, 6, 50, 10, 25, DateTimeKind.Local).AddTicks(2918),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 3,
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 11, 6, 50, 10, 25, DateTimeKind.Local).AddTicks(3059),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKH");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.ToTable("KhachHang", t =>
                        {
                            t.HasCheckConstraint("CK_KH_Email_Format", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_KH_Sdt_Format", "LEN([Sdt]) >= 10 AND [Sdt] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            Email = "khach.tran@gmail.com",
                            HoTen = "Trần Thị Khách",
                            MaTK = "6e30006e-b30f-47b9-9e33-4a02d89d5b57",
                            NgaySinh = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0912345678"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<double>("PhanTramGiam")
                        .HasColumnType("float");

                    b.Property<decimal>("SoTienToiDaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMai", t =>
                        {
                            t.HasCheckConstraint("CK_KM_PhanTram", "[PhanTramGiam] >= 0 AND [PhanTramGiam] <= 100");

                            t.HasCheckConstraint("CK_KM_ThoiGian", "[NgayKetThuc] > [NgayBatDau]");
                        });

                    b.HasData(
                        new
                        {
                            MaKM = "KM10",
                            NgayBatDau = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 10.0,
                            SoTienToiDaGiam = 50000m,
                            TenChuongTrinh = "Giảm giá khai trương",
                            TrangThai = true
                        },
                        new
                        {
                            MaKM = "SUMMER26",
                            NgayBatDau = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 15.0,
                            SoTienToiDaGiam = 100000m,
                            TenChuongTrinh = "Ưu đãi mùa hè",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<decimal>("GiaVeCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaTau")
                        .HasColumnType("int");

                    b.Property<int>("MaTuyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGioCapBenDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGioKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGheTrong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("MaTuyen");

                    b.HasIndex("MaTau", "NgayGioKhoiHanh")
                        .IsUnique();

                    b.ToTable("LichTrinh", t =>
                        {
                            t.HasCheckConstraint("CK_LT_GheTrong", "[SoGheTrong] >= 0");

                            t.HasCheckConstraint("CK_LT_GiaVe", "[GiaVeCoBan] >= 0");

                            t.HasCheckConstraint("CK_LT_ThoiGian", "[NgayGioCapBenDuKien] > [NgayGioKhoiHanh]");
                        });

                    b.HasData(
                        new
                        {
                            MaLichTrinh = 1,
                            GiaVeCoBan = 200000m,
                            MaTau = 1,
                            MaTuyen = 1,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 12, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 12, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Log", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("BangTacDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaTK");

                    b.ToTable("Log");

                    b.HasData(
                        new
                        {
                            MaLog = 1,
                            BangTacDong = "Hệ thống",
                            HanhDong = "Khởi tạo hệ thống",
                            MaTK = "6e30006e-b30f-47b9-9e33-4a02d89d5b57",
                            NoiDungChiTiet = "Seed dữ liệu mẫu thành công",
                            ThoiGian = new DateTime(2026, 4, 11, 6, 50, 10, 25, DateTimeKind.Local).AddTicks(3548)
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNV");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique();

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.ToTable("NhanVien", t =>
                        {
                            t.HasCheckConstraint("CK_NV_Email_Format", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_NV_Sdt_Format", "LEN([Sdt]) >= 10 AND [Sdt] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            ChucVu = "Bán vé",
                            Email = "chay.nv@boat.com",
                            HoTen = "Nguyễn Văn Chạy",
                            Luong = 0m,
                            MaTK = "6e30006e-b30f-47b9-9e33-4a02d89d5b57",
                            Sdt = "0987654321",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Tau", b =>
                {
                    b.Property<int>("MaTau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTau"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTau");

                    b.HasIndex("TenTau")
                        .IsUnique();

                    b.ToTable("Tau");

                    b.HasData(
                        new
                        {
                            MaTau = 1,
                            HinhAnh = "0ed53f9a-2e39-46ab-897c-856e7cde576d.jpg",
                            TenTau = "Tàu Cao Tốc 01",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 2,
                            HinhAnh = "2073e0cb-cf50-45b1-aa5e-9d40af4b7477.jpg",
                            TenTau = "Tàu Express 01",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 3,
                            HinhAnh = "872b8a7a-79ae-4f8b-96da-53c7e3caa5e3.jpg",
                            TenTau = "Tàu Cao Tốc 02",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 4,
                            HinhAnh = "d0c7cc56-fd6c-4750-8095-2c250c2c3eed.jpg",
                            TenTau = "Tàu Express 02",
                            TongSoGhe = 20,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.TuyenDuong", b =>
                {
                    b.Property<int>("MaTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuyen"));

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("KhoangCach")
                        .HasColumnType("float");

                    b.Property<string>("TenTuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("ThoiGianDuKien")
                        .HasColumnType("time");

                    b.HasKey("MaTuyen");

                    b.HasIndex("DiemDi", "DiemDen")
                        .IsUnique();

                    b.ToTable("TuyenDuong");

                    b.HasData(
                        new
                        {
                            MaTuyen = 1,
                            DiemDen = "Vũng Tàu",
                            DiemDi = "Sài Gòn",
                            HinhAnh = "80eec6b7-1650-400a-afda-eec7573a7f48.jfif",
                            KhoangCach = 100.0,
                            TenTuyen = "Sài Gòn - Vũng Tàu",
                            ThoiGianDuKien = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 2,
                            DiemDen = "Phú Quốc",
                            DiemDi = "Rạch Giá",
                            HinhAnh = "dcc6e003-7560-4d50-8933-98682d3da2ef.jfif",
                            KhoangCach = 120.0,
                            TenTuyen = "Rạch Giá - Phú Quốc",
                            ThoiGianDuKien = new TimeSpan(0, 2, 45, 0, 0)
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KhachHangMaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVe");

                    b.HasIndex("KhachHangMaKH");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaLichTrinh");

                    b.ToTable("Ve");

                    b.HasData(
                        new
                        {
                            MaVe = 1,
                            GiaVe = 180000m,
                            MaGhe = 2,
                            MaHoaDon = 1,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 2,
                            GiaVe = 180000m,
                            MaGhe = 3,
                            MaHoaDon = 2,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 3,
                            GiaVe = 180000m,
                            MaGhe = 4,
                            MaHoaDon = 3,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.DanhGia", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.LichTrinh", null)
                        .WithMany("DanhGias")
                        .HasForeignKey("LichTrinhMaLichTrinh")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.Ve", "Ve")
                        .WithOne("DanhGia")
                        .HasForeignKey("WebAppBookingBoat.Models.DanhGia", "MaVe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Tau", "Tau")
                        .WithMany("Ghes")
                        .HasForeignKey("MaTau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tau");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Tau", "Tau")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.TuyenDuong", "TuyenDuong")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tau");

                    b.Navigation("TuyenDuong");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Log", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.KhachHang", null)
                        .WithMany("Ves")
                        .HasForeignKey("KhachHangMaKH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.Ghe", "Ghe")
                        .WithMany()
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.HoaDon", "HoaDon")
                        .WithMany("Ves")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.LichTrinh", "LichTrinh")
                        .WithMany("Ves")
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("HoaDon");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Tau", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("LichTrinhs");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.TuyenDuong", b =>
                {
                    b.Navigation("LichTrinhs");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.Navigation("DanhGia");
                });
#pragma warning restore 612, 618
        }
    }
}
