// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppBookingBoat.Repository;

#nullable disable

namespace WebAppBookingBoat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c4b3adc5-a6a7-4f7e-bd1c-2806c328191b",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "7667fed0-c6f2-4dff-a12b-f4c5b064f9f2",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c4b3adc5-a6a7-4f7e-bd1c-2806c328191b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d384f5bf-81ff-4ec0-a2aa-4377f3d94e92",
                            Email = "admin@booking.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BOOKING.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHJXYAQhZDUNBWTNcgkCaOtc0r/eWeEjYGwJuD+g6pA9VwSNbM2RdpuZGFyJEIKi4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dbabf772-6b59-46e1-b9b9-fa8cdb51540c",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "7667fed0-c6f2-4dff-a12b-f4c5b064f9f2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce5f96d5-d52f-4039-823c-03cc9bdf85e1",
                            Email = "nhanvien1@booking.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NHANVIEN1@BOOKING.COM",
                            NormalizedUserName = "NHANVIEN1",
                            PasswordHash = "AQAAAAIAAYagAAAAECayK2xNLqsc1zsvb73kbhS/nDkAY1I3PdRbh3pzXXBAD/mxGz0KgYsBd6AkyhQA3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a652bf4d-9407-4c99-8465-b148e2e74f8d",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "nhanvien1"
                        },
                        new
                        {
                            Id = "711c81c5-997b-4ad1-824d-00a0e4237029",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb1a1ad1-1e26-4922-bb49-a681fc01ed30",
                            Email = "khachhang1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHACHHANG1@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG1",
                            PasswordHash = "AQAAAAIAAYagAAAAEM9+bYZRzcU+dnCRpUQHItrpsS1gk9yELh79T+ZFRcVCnVMr8MTCBKU+ocW6YW8yWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bcf47bd2-8b4b-448b-b00c-600b43bbfc35",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "khachhang1"
                        },
                        new
                        {
                            Id = "7d328812-88db-422a-b83e-14d56dd91dde",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3a1c257-08d9-4465-ab34-9f8d35edcf54",
                            Email = "khachhang2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHACHHANG2@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG2",
                            PasswordHash = "AQAAAAIAAYagAAAAEHYWSeke9O9rJZSsYcx6+eOZ4RVuYO+Un1UODBRIE57gLfTk79Iiuu6yP7zbeY2CNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4d08d3d4-341d-40d2-8a7c-ecf6e93a2430",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "khachhang2"
                        },
                        new
                        {
                            Id = "8e3ade7b-c691-4276-abd5-3e1fb0f02a05",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4835b6a-3669-48ce-8496-69ede6e1aa1e",
                            Email = "testuser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER@GMAIL.COM",
                            NormalizedUserName = "TESTUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEDsoNw73Xg+hXDD1Fm8EMpLANvMCkU6oXJj+37wryxCNKpl6mpzJZC9oRUnizM2qgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10249c4c-755a-48e9-92b9-46b4cf9fcd3a",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "testuser"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("HoaDonMaHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("LichTrinhMaLichTrinh")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhanHoiAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.HasIndex("LichTrinhMaLichTrinh");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("DanhGia", t =>
                        {
                            t.HasCheckConstraint("CK_DG_NgayPhanHoi", "[NgayPhanHoi] IS NULL OR [NgayPhanHoi] >= [NgayDanhGia]");

                            t.HasCheckConstraint("CK_DG_SoSao", "[SoSao] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_DG_TrangThai", "[TrangThai] IN (N'Chờ duyệt', N'Đã hiển thị', N'Đã ẩn')");
                        });

                    b.HasData(
                        new
                        {
                            MaDanhGia = 1,
                            HinhAnh = "6a4b2c8d-1e5f-4a3b-9c2d-8e7f6a5b4c3d_review-phu-quoc.jpg",
                            MaHoaDon = 1,
                            NgayDanhGia = new DateTime(2026, 4, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            NgayPhanHoi = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Chuyến đi tuyệt vời, tàu chạy rất êm và đúng giờ. Nhân viên hỗ trợ nhiệt tình!",
                            PhanHoiAdmin = "Cảm ơn bạn đã ủng hộ WebAppBookingBoat! Rất mong được phục vụ bạn trong những chuyến đi tới.",
                            SoSao = 5,
                            TrangThai = "Đã hiển thị"
                        },
                        new
                        {
                            MaDanhGia = 2,
                            HinhAnh = "8e7d6c5b-4a3f-4e2d-9c1b-0a9b8c7d6e5f_review-thang-long.jpg",
                            MaHoaDon = 2,
                            NgayDanhGia = new DateTime(2026, 4, 11, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            NgayPhanHoi = new DateTime(2026, 4, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Chất lượng ghế VIP rất tốt, tuy nhiên đồ ăn nhẹ trên tàu hơi ít lựa chọn.",
                            PhanHoiAdmin = "Chào bạn, Admin ghi nhận góp ý và sẽ làm việc với bếp tàu để cải thiện thực đơn ạ!",
                            SoSao = 4,
                            TrangThai = "Đã hiển thị"
                        },
                        new
                        {
                            MaDanhGia = 3,
                            HinhAnh = "2c3d4e5f-6a7b-4c8d-9e0f-1a2b3c4d5e6f_view-bien.jpg",
                            MaHoaDon = 3,
                            NgayDanhGia = new DateTime(2026, 4, 17, 20, 11, 39, 554, DateTimeKind.Local).AddTicks(6008),
                            NoiDung = "Đặt vé cực nhanh, thanh toán tiện lợi. Sẽ quay lại!",
                            SoSao = 5,
                            TrangThai = "Chờ duyệt"
                        },
                        new
                        {
                            MaDanhGia = 4,
                            HinhAnh = "5f4e3d2c-1b0a-4c9d-8e7f-6a5b4c3d2e1f_tau-phu-quy.jpg",
                            MaHoaDon = 4,
                            NgayDanhGia = new DateTime(2026, 4, 17, 22, 11, 39, 554, DateTimeKind.Local).AddTicks(6014),
                            NoiDung = "Gia đình mình đi tuyến Hà Tiên - Phú Quốc rất hài lòng...",
                            SoSao = 5,
                            TrangThai = "Chờ duyệt"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("LoaiGhe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaTau")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaTau", "TenGhe")
                        .IsUnique();

                    b.ToTable("Ghe", t =>
                        {
                            t.HasCheckConstraint("CK_Ghe_LoaiGhe", "[LoaiGhe] IN (N'Thường', N'VIP')");
                        });

                    b.HasData(
                        new
                        {
                            MaGhe = 1,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 2,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 3,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 4,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 5,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 6,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 7,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 8,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 9,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 10,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 11,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 12,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 13,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 14,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 15,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 16,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 17,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 18,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 19,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 20,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-20"
                        },
                        new
                        {
                            MaGhe = 21,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 22,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 23,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 24,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 25,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 26,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 27,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 28,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 29,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 30,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 31,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 32,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 33,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 34,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 35,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 36,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 37,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 38,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 39,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 40,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-20"
                        },
                        new
                        {
                            MaGhe = 41,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 42,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 43,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 44,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 45,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 46,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 47,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 48,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 49,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 50,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 51,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 52,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 53,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 54,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 55,
                            LoaiGhe = "Thường",
                            MaTau = 3,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 56,
                            LoaiGhe = "VIP",
                            MaTau = 3,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 57,
                            LoaiGhe = "VIP",
                            MaTau = 3,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 58,
                            LoaiGhe = "VIP",
                            MaTau = 3,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 59,
                            LoaiGhe = "VIP",
                            MaTau = 3,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 60,
                            LoaiGhe = "VIP",
                            MaTau = 3,
                            TenGhe = "V-20"
                        },
                        new
                        {
                            MaGhe = 61,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 62,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 63,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 64,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 65,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 66,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 67,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 68,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 69,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 70,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 71,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 72,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 73,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 74,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 75,
                            LoaiGhe = "Thường",
                            MaTau = 4,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 76,
                            LoaiGhe = "VIP",
                            MaTau = 4,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 77,
                            LoaiGhe = "VIP",
                            MaTau = 4,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 78,
                            LoaiGhe = "VIP",
                            MaTau = 4,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 79,
                            LoaiGhe = "VIP",
                            MaTau = 4,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 80,
                            LoaiGhe = "VIP",
                            MaTau = 4,
                            TenGhe = "V-20"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<string>("MaKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongVe")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TamTinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKM");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_HD_SoLuong", "[SoLuongVe] > 0");

                            t.HasCheckConstraint("CK_HD_Tien", "[TamTinh] >= 0 AND [SoTienGiam] >= 0 AND [TongTien] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            MaHoaDon = 1,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 17, 22, 11, 39, 554, DateTimeKind.Local).AddTicks(5477),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 2,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 17, 22, 11, 39, 554, DateTimeKind.Local).AddTicks(5614),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 4,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 17, 22, 11, 39, 554, DateTimeKind.Local).AddTicks(5619),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 3,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 17, 22, 11, 39, 554, DateTimeKind.Local).AddTicks(5667),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKH");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.ToTable("KhachHang", t =>
                        {
                            t.HasCheckConstraint("CK_KH_Email_Format", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_KH_Sdt_Format", "LEN([Sdt]) >= 10 AND [Sdt] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            Email = "khach.tran@gmail.com",
                            HoTen = "Trần Thị Khách",
                            MaTK = "8e3ade7b-c691-4276-abd5-3e1fb0f02a05",
                            NgaySinh = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0912345678"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<double>("PhanTramGiam")
                        .HasColumnType("float");

                    b.Property<decimal>("SoTienToiDaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMai", t =>
                        {
                            t.HasCheckConstraint("CK_KM_PhanTram", "[PhanTramGiam] >= 0 AND [PhanTramGiam] <= 100");

                            t.HasCheckConstraint("CK_KM_SoTienToiDa", "[SoTienToiDaGiam] >= 0");

                            t.HasCheckConstraint("CK_KM_ThoiGian", "[NgayKetThuc] > [NgayBatDau]");
                        });

                    b.HasData(
                        new
                        {
                            MaKM = "KM10",
                            HinhAnh = "322b0521-7bf6-40e5-aeea-b28fcfb0c5fd.jpg",
                            MoTa = "Chào mừng hệ thống WebAppBookingBoat đi vào hoạt động. Giảm ngay 50% cho tất cả các tuyến tàu cao tốc.",
                            NgayBatDau = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 50.0,
                            SoTienToiDaGiam = 200000m,
                            TenChuongTrinh = "Giảm giá khai trương",
                            TrangThai = "Chưa diễn ra"
                        },
                        new
                        {
                            MaKM = "SUMMER26",
                            HinhAnh = "9c2fb5b6-9d1e-4a2c-91be-51c61d3d10d9.jpg",
                            MoTa = "Tận hưởng kỳ nghỉ hè với ưu đãi cực khủng lên đến 10% khi đặt vé.",
                            NgayBatDau = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 10.0,
                            SoTienToiDaGiam = 100000m,
                            TenChuongTrinh = "Ưu đãi mùa hè rực rỡ",
                            TrangThai = "Chưa diễn ra"
                        },
                        new
                        {
                            MaKM = "SUMMER27",
                            HinhAnh = "8b779b59-820c-48bd-bc11-b85e27021424.jpg",
                            MoTa = "Tận hưởng kỳ nghỉ hè với ưu đãi cực khủng lên đến 30% khi đặt vé.",
                            NgayBatDau = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 30.0,
                            SoTienToiDaGiam = 100000m,
                            TenChuongTrinh = "Ưu đãi mùa hè hết cỡ",
                            TrangThai = "Chưa diễn ra"
                        },
                        new
                        {
                            MaKM = "TET2026",
                            HinhAnh = "0b00c585-fb35-4462-9b5d-8e1aee28b429.jpg",
                            MoTa = "Chương trình khuyến mãi đặc biệt dành cho khách hàng về quê ăn Tết hoặc du xuân cùng gia đình.",
                            NgayBatDau = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 30.0,
                            SoTienToiDaGiam = 300000m,
                            TenChuongTrinh = "Vui Tết sum vầy",
                            TrangThai = "Chưa diễn ra"
                        },
                        new
                        {
                            MaKM = "GIADO304",
                            HinhAnh = "a64e7e7d-4495-4950-b2ec-ec62db4cfdbb.jpg",
                            MoTa = "Ưu đãi cực lớn dành cho các tuyến tàu cao tốc du lịch trong kỳ nghỉ lễ 30/4 và 1/5.",
                            NgayBatDau = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 30.0,
                            SoTienToiDaGiam = 400000m,
                            TenChuongTrinh = "Mừng Đại Lễ - Giảm Giá Mê",
                            TrangThai = "Sắp diễn ra"
                        },
                        new
                        {
                            MaKM = "DONGAM2026",
                            HinhAnh = "215b54dc-a2eb-4d82-8091-e4e885928754.jpg",
                            MoTa = "Ưu đãi sưởi ấm những chuyến đi cuối năm. Giảm giá sâu cho các tuyến tàu ra đảo nghỉ dưỡng.",
                            NgayBatDau = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 25.0,
                            SoTienToiDaGiam = 250000m,
                            TenChuongTrinh = "Mùa Đông Ấm Áp",
                            TrangThai = "Chưa diễn ra"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<decimal>("GiaVeCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaTau")
                        .HasColumnType("int");

                    b.Property<int>("MaTuyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGioCapBenDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGioKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGheTrong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("MaTuyen");

                    b.HasIndex("MaTau", "NgayGioKhoiHanh")
                        .IsUnique();

                    b.ToTable("LichTrinh", t =>
                        {
                            t.HasCheckConstraint("CK_LT_GheTrong", "[SoGheTrong] >= 0");

                            t.HasCheckConstraint("CK_LT_GiaVe", "[GiaVeCoBan] >= 0");

                            t.HasCheckConstraint("CK_LT_ThoiGian", "[NgayGioCapBenDuKien] > [NgayGioKhoiHanh]");

                            t.HasCheckConstraint("CK_LT_TrangThai", "[TrangThai] IN (N'Sắp khởi hành', N'Đang vận hành', N'Hoàn thành', N'Đã hủy')");
                        });

                    b.HasData(
                        new
                        {
                            MaLichTrinh = 1,
                            GiaVeCoBan = 200000m,
                            MaTau = 1,
                            MaTuyen = 1,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 18, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 18, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 2,
                            GiaVeCoBan = 200000m,
                            MaTau = 2,
                            MaTuyen = 2,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 18, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 18, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 3,
                            GiaVeCoBan = 200000m,
                            MaTau = 3,
                            MaTuyen = 3,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 19, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 19, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 4,
                            GiaVeCoBan = 200000m,
                            MaTau = 4,
                            MaTuyen = 4,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 21, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 21, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 5,
                            GiaVeCoBan = 200000m,
                            MaTau = 5,
                            MaTuyen = 5,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 22, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 6,
                            GiaVeCoBan = 200000m,
                            MaTau = 6,
                            MaTuyen = 6,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 24, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 24, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 7,
                            GiaVeCoBan = 200000m,
                            MaTau = 7,
                            MaTuyen = 7,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 24, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 24, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 8,
                            GiaVeCoBan = 200000m,
                            MaTau = 1,
                            MaTuyen = 1,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 25, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 25, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 9,
                            GiaVeCoBan = 200000m,
                            MaTau = 2,
                            MaTuyen = 2,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 26, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 26, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        },
                        new
                        {
                            MaLichTrinh = 10,
                            GiaVeCoBan = 200000m,
                            MaTau = 3,
                            MaTuyen = 3,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 26, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 26, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Log", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("BangTacDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiLog")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaTK");

                    b.ToTable("Logs", t =>
                        {
                            t.HasCheckConstraint("CK_Log_Loai", "[LoaiLog] IN ('Info', 'Warning', 'Error', 'Critical')");
                        });

                    b.HasData(
                        new
                        {
                            MaLog = 1,
                            BangTacDong = "System",
                            HanhDong = "Khởi tạo hệ thống",
                            IpAddress = "127.0.0.1",
                            LoaiLog = "Info",
                            MaTK = "c4b3adc5-a6a7-4f7e-bd1c-2806c328191b",
                            NoiDungChiTiet = "Hệ thống đã khởi tạo dữ liệu mẫu (Seed Data) thành công.",
                            ThoiGian = new DateTime(2026, 4, 13, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLog = 2,
                            BangTacDong = "AspNetUsers",
                            HanhDong = "Cấu hình bảo mật",
                            IpAddress = "127.0.0.1",
                            LoaiLog = "Info",
                            MaTK = "c4b3adc5-a6a7-4f7e-bd1c-2806c328191b",
                            NoiDungChiTiet = "Thiết lập quyền Quản trị viên (Admin) cho hệ thống.",
                            ThoiGian = new DateTime(2026, 4, 13, 9, 0, 5, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNV");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.ToTable("NhanVien", t =>
                        {
                            t.HasCheckConstraint("CK_NV_Email_Format", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_NV_Sdt_Format", "LEN([Sdt]) >= 10 AND [Sdt] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            ChucVu = "Admin",
                            Email = "maihuy@booking.com",
                            HoTen = "Mai Nhứt Huy",
                            Luong = 0m,
                            MaTK = "c4b3adc5-a6a7-4f7e-bd1c-2806c328191b",
                            Sdt = "0386747090",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Tau", b =>
                {
                    b.Property<int>("MaTau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTau"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTau");

                    b.HasIndex("TenTau")
                        .IsUnique();

                    b.ToTable("Tau");

                    b.HasData(
                        new
                        {
                            MaTau = 1,
                            HinhAnh = "0885ba23-96cd-46c0-9cce-5b739d92c445_Tau-cao-toc-Phu-Quoc-Express-Vung-Tau-Con-Dao.jpg",
                            TenTau = "Phú Quốc Express 1",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 2,
                            HinhAnh = "4f471677-b064-46f6-ba00-1840314b7226_tau-trung-trac-tren-tuyen-cao-toc-phan-thiet-phu-quy-1024x768-1.jpg",
                            TenTau = "Phú Quốc Express 2",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 3,
                            HinhAnh = "ca4c374d-3d0c-48be-8b36-e79219a62796_Tau-cao-toc-Con-Dao-Express-36-1536x863.jpg",
                            TenTau = "Phú Quốc Express 3",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 4,
                            HinhAnh = "dfa33889-692e-4f3a-84c2-491e2a402329_Tau-cao-toc-Trung-Nhi.jpg",
                            TenTau = "Phú Quốc Express 4",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 5,
                            HinhAnh = "ca4c374d-3d0c-48be-8b36-e79219a62796_Tau-cao-toc-Con-Dao-Express-36-1536x863.jpg",
                            TenTau = "Phú Quốc Express 5",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 6,
                            HinhAnh = "0885ba23-96cd-46c0-9cce-5b739d92c445_Tau-cao-toc-Phu-Quoc-Express-Vung-Tau-Con-Dao.jpg",
                            TenTau = "Phú Quốc Express 6",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 7,
                            HinhAnh = "0885ba23-96cd-46c0-9cce-5b739d92c445_Tau-cao-toc-Phu-Quoc-Express-Vung-Tau-Con-Dao.jpg",
                            TenTau = "Phú Quốc Express 7",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 8,
                            HinhAnh = "dfa33889-692e-4f3a-84c2-491e2a402329_Tau-cao-toc-Trung-Nhi.jpg",
                            TenTau = "Phú Quốc Express 8",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 9,
                            HinhAnh = "4f471677-b064-46f6-ba00-1840314b7226_tau-trung-trac-tren-tuyen-cao-toc-phan-thiet-phu-quy-1024x768-1.jpg",
                            TenTau = "Phú Quốc Express 9",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 10,
                            HinhAnh = "4f471677-b064-46f6-ba00-1840314b7226_tau-trung-trac-tren-tuyen-cao-toc-phan-thiet-phu-quy-1024x768-1.jpg",
                            TenTau = "Phú Quốc Express 10",
                            TongSoGhe = 20,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.TuyenDuong", b =>
                {
                    b.Property<int>("MaTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuyen"));

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("KhoangCach")
                        .HasColumnType("float");

                    b.Property<string>("TenTuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("ThoiGianDuKien")
                        .HasColumnType("time");

                    b.HasKey("MaTuyen");

                    b.HasIndex("DiemDi", "DiemDen")
                        .IsUnique();

                    b.ToTable("TuyenDuong", t =>
                        {
                            t.HasCheckConstraint("CK_TD_DiemKhacNhau", "[DiemDi] <> [DiemDen]");
                        });

                    b.HasData(
                        new
                        {
                            MaTuyen = 1,
                            DiemDen = "Phú Quý",
                            DiemDi = "Phan Thiết",
                            HinhAnh = "04e1440f-0c96-46c6-82b1-c10f63b4db23_phu-quy.jpg",
                            KhoangCach = 105.0,
                            TenTuyen = "Phan Thiết - Phú Quý",
                            ThoiGianDuKien = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 2,
                            DiemDen = "Cát Bà",
                            DiemDi = "Hải Phòng",
                            HinhAnh = "c31132fa-0e14-4787-8d05-fd22a23a3411_cat-ba.jpg",
                            KhoangCach = 30.0,
                            TenTuyen = "Hải Phòng - Cát Bà",
                            ThoiGianDuKien = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 3,
                            DiemDen = "Côn Đảo",
                            DiemDi = "Vũng Tàu",
                            HinhAnh = "7abf98e9-a440-4779-8a3a-529b3a400bbd_con-dao.jpg",
                            KhoangCach = 180.0,
                            TenTuyen = "Vũng Tàu - Côn Đảo",
                            ThoiGianDuKien = new TimeSpan(0, 3, 45, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 4,
                            DiemDen = "Hòn Sơn",
                            DiemDi = "Rạch Giá",
                            HinhAnh = "c051024a-ca91-4835-8751-6a6b40f5c124_hon-son.jpg",
                            KhoangCach = 65.0,
                            TenTuyen = "Rạch Giá - Hòn Sơn",
                            ThoiGianDuKien = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 5,
                            DiemDen = "Lý Sơn",
                            DiemDi = "Sa Kỳ",
                            HinhAnh = "a3c8c7b7-69df-4c73-9acd-11db5b8433e8_ly-son.jpg",
                            KhoangCach = 30.0,
                            TenTuyen = "Sa Kỳ - Lý Sơn",
                            ThoiGianDuKien = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 6,
                            DiemDen = "Nam Du",
                            DiemDi = "Rạch Giá",
                            HinhAnh = "6f1e4c0e-2db1-4540-b7a0-bdafd5a151cd_nam-du.jpg",
                            KhoangCach = 80.0,
                            TenTuyen = "Rạch Giá - Nam Du",
                            ThoiGianDuKien = new TimeSpan(0, 2, 15, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 7,
                            DiemDen = "Phú Quốc",
                            DiemDi = "Hà Tiên",
                            HinhAnh = "bcd3de60-2b13-4d14-95c5-37ca27af887d_phu-quoc.jpg",
                            KhoangCach = 45.0,
                            TenTuyen = "Hà Tiên - Phú Quốc",
                            ThoiGianDuKien = new TimeSpan(0, 1, 15, 0, 0)
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVe");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaLichTrinh", "MaGhe")
                        .IsUnique();

                    b.ToTable("Ve", t =>
                        {
                            t.HasCheckConstraint("CK_Ve_GiaVe", "[GiaVe] >= 0");

                            t.HasCheckConstraint("CK_Ve_TrangThai", "[TrangThai] IN (N'Đang chờ', N'Hợp lệ', N'Đã hủy')");
                        });

                    b.HasData(
                        new
                        {
                            MaVe = 1,
                            GiaVe = 180000m,
                            MaGhe = 2,
                            MaHoaDon = 1,
                            MaLichTrinh = 2,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 2,
                            GiaVe = 180000m,
                            MaGhe = 3,
                            MaHoaDon = 2,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 3,
                            GiaVe = 180000m,
                            MaGhe = 4,
                            MaHoaDon = 3,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 4,
                            GiaVe = 180000m,
                            MaGhe = 5,
                            MaHoaDon = 4,
                            MaLichTrinh = 2,
                            TrangThai = "Hợp lệ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.DanhGia", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.HoaDon", null)
                        .WithMany("DanhGias")
                        .HasForeignKey("HoaDonMaHoaDon");

                    b.HasOne("WebAppBookingBoat.Models.LichTrinh", null)
                        .WithMany("DanhGias")
                        .HasForeignKey("LichTrinhMaLichTrinh")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.HoaDon", "HoaDon")
                        .WithOne("DanhGia")
                        .HasForeignKey("WebAppBookingBoat.Models.DanhGia", "MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Tau", "Tau")
                        .WithMany("Ghes")
                        .HasForeignKey("MaTau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tau");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("WebAppBookingBoat.Models.KhachHang", "MaTK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Tau", "Tau")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.TuyenDuong", "TuyenDuong")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tau");

                    b.Navigation("TuyenDuong");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Log", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("WebAppBookingBoat.Models.NhanVien", "MaTK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Ghe", "Ghe")
                        .WithMany("Ves")
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.HoaDon", "HoaDon")
                        .WithMany("Ves")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.LichTrinh", "LichTrinh")
                        .WithMany("Ves")
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("HoaDon");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DanhGias");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Tau", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("LichTrinhs");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.TuyenDuong", b =>
                {
                    b.Navigation("LichTrinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
