// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppBookingBoat.Repository;

#nullable disable

namespace WebAppBookingBoat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Nhân viên",
                            NormalizedName = "NHÂN VIÊN"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Khách hàng",
                            NormalizedName = "KHÁCH HÀNG"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8b723ad0-b8ec-4a0f-80fe-651b03e1a53b",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0ae2743c-fcfa-4b50-92f6-129aa8352a4a",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8b723ad0-b8ec-4a0f-80fe-651b03e1a53b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef43d128-e6e8-4c7c-822b-3ec3621532f8",
                            Email = "admin@booking.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BOOKING.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKsp7Gmq1QdUe0CyciI5U8KHwSTFYbQRC7sTMmgsfPSvzjL7t35k5k/qTBUPprjgOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46512a09-9054-4f0b-8d18-48b971cae82c",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "0ae2743c-fcfa-4b50-92f6-129aa8352a4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71bd63cc-4f8d-4a81-911c-16668e768743",
                            Email = "nhanvien1@booking.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NHANVIEN1@BOOKING.COM",
                            NormalizedUserName = "NHANVIEN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEMPhWTAPBrB7pDV6BwgbzL0b3C2fgJ8Onb3Vx0lNul1RG+1wD6zGJThLEyLWWZ8ymg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb4e943b-5e33-45d3-8178-a3c36eec1b28",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "nhanvien1"
                        },
                        new
                        {
                            Id = "daa09660-485a-48b6-a193-dd3159d0ad7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2623463c-5b60-45b7-a5dd-928a5edfdcc0",
                            Email = "khachhang1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHACHHANG1@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG1",
                            PasswordHash = "AQAAAAIAAYagAAAAEO5bR9cKdeVq5KBoYSOQT8fa3//q/T4lBNmG+eAaZy0tFU2hjcO6OLL1Zs6Fa8Hp6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a700aec-c70c-4cc5-b39a-222d978b718f",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "khachhang1"
                        },
                        new
                        {
                            Id = "befcdc74-a8ec-4cb6-b282-125292bede20",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e8de378-961b-4265-9dfb-d85e96401b50",
                            Email = "khachhang2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHACHHANG2@GMAIL.COM",
                            NormalizedUserName = "KHACHHANG2",
                            PasswordHash = "AQAAAAIAAYagAAAAEPAXAPqZyrmIIEFZm1Lh0bRCVzXzdl/llBqnVJFkySPBdvDPQmMc0T98PeBAghhlZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cea23eb4-7462-4aa4-bc59-4655273aeeac",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "khachhang2"
                        },
                        new
                        {
                            Id = "a72122c2-1421-4b9a-9759-ca33578591ce",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "373498ac-a6f6-4fc5-977e-c5dbc11430d5",
                            Email = "testuser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER@GMAIL.COM",
                            NormalizedUserName = "TESTUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEDVPAaIcT60H68barzi52hwYl8YDCTX1irvLYAXSXELpVzec/fnHCt/5+QyJn5X0Fg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "60ce01e5-d1bc-482e-8cb1-19d8b2f6538b",
                            TrangThai = true,
                            TwoFactorEnabled = false,
                            UserName = "testuser"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LichTrinhMaLichTrinh")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhanHoiAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("LichTrinhMaLichTrinh");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("DanhGia", t =>
                        {
                            t.HasCheckConstraint("CK_DG_NgayPhanHoi", "[NgayPhanHoi] IS NULL OR [NgayPhanHoi] >= [NgayDanhGia]");

                            t.HasCheckConstraint("CK_DG_SoSao", "[SoSao] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_DG_TrangThai", "[TrangThai] IN (N'Chờ duyệt', N'Đã hiển thị', N'Đã ẩn')");
                        });

                    b.HasData(
                        new
                        {
                            MaDanhGia = 1,
                            HinhAnh = "review-tau-01.jpg",
                            MaHoaDon = 1,
                            NgayDanhGia = new DateTime(2026, 4, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            NgayPhanHoi = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Chuyến đi tuyệt vời, tàu chạy rất êm và đúng giờ. Nhân viên hỗ trợ nhiệt tình!",
                            PhanHoiAdmin = "Cảm ơn bạn đã ủng hộ WebAppBookingBoat! Rất mong được phục vụ bạn trong những chuyến đi tới.",
                            SoSao = 5,
                            TrangThai = "Đã hiển thị"
                        },
                        new
                        {
                            MaDanhGia = 2,
                            HinhAnh = "review-ghe-vip.jpg",
                            MaHoaDon = 2,
                            NgayDanhGia = new DateTime(2026, 4, 11, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            NgayPhanHoi = new DateTime(2026, 4, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Chất lượng ghế VIP rất tốt, tuy nhiên đồ ăn nhẹ trên tàu hơi ít lựa chọn.",
                            PhanHoiAdmin = "Chào bạn, Admin ghi nhận góp ý và sẽ làm việc với bếp tàu để cải thiện thực đơn ạ!",
                            SoSao = 4,
                            TrangThai = "Đã hiển thị"
                        },
                        new
                        {
                            MaDanhGia = 3,
                            MaHoaDon = 3,
                            NgayDanhGia = new DateTime(2026, 4, 13, 19, 39, 37, 722, DateTimeKind.Local).AddTicks(2459),
                            NoiDung = "Đặt vé cực nhanh, thanh toán tiện lợi. Sẽ quay lại!",
                            SoSao = 5,
                            TrangThai = "Chờ duyệt"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("LoaiGhe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaTau")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaTau", "TenGhe")
                        .IsUnique();

                    b.ToTable("Ghe", t =>
                        {
                            t.HasCheckConstraint("CK_Ghe_LoaiGhe", "[LoaiGhe] IN (N'Thường', N'VIP')");
                        });

                    b.HasData(
                        new
                        {
                            MaGhe = 1,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 2,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 3,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 4,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 5,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 6,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 7,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 8,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 9,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 10,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 11,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 12,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 13,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 14,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 15,
                            LoaiGhe = "Thường",
                            MaTau = 1,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 16,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 17,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 18,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 19,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 20,
                            LoaiGhe = "VIP",
                            MaTau = 1,
                            TenGhe = "V-20"
                        },
                        new
                        {
                            MaGhe = 21,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-01"
                        },
                        new
                        {
                            MaGhe = 22,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-02"
                        },
                        new
                        {
                            MaGhe = 23,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-03"
                        },
                        new
                        {
                            MaGhe = 24,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-04"
                        },
                        new
                        {
                            MaGhe = 25,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-05"
                        },
                        new
                        {
                            MaGhe = 26,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-06"
                        },
                        new
                        {
                            MaGhe = 27,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-07"
                        },
                        new
                        {
                            MaGhe = 28,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-08"
                        },
                        new
                        {
                            MaGhe = 29,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-09"
                        },
                        new
                        {
                            MaGhe = 30,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-10"
                        },
                        new
                        {
                            MaGhe = 31,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-11"
                        },
                        new
                        {
                            MaGhe = 32,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-12"
                        },
                        new
                        {
                            MaGhe = 33,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-13"
                        },
                        new
                        {
                            MaGhe = 34,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-14"
                        },
                        new
                        {
                            MaGhe = 35,
                            LoaiGhe = "Thường",
                            MaTau = 2,
                            TenGhe = "T-15"
                        },
                        new
                        {
                            MaGhe = 36,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-16"
                        },
                        new
                        {
                            MaGhe = 37,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-17"
                        },
                        new
                        {
                            MaGhe = 38,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-18"
                        },
                        new
                        {
                            MaGhe = 39,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-19"
                        },
                        new
                        {
                            MaGhe = 40,
                            LoaiGhe = "VIP",
                            MaTau = 2,
                            TenGhe = "V-20"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<string>("MaKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongVe")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TamTinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKM");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_HD_SoLuong", "[SoLuongVe] > 0");

                            t.HasCheckConstraint("CK_HD_Tien", "[TamTinh] >= 0 AND [SoTienGiam] >= 0 AND [TongTien] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            MaHoaDon = 1,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 13, 21, 39, 37, 722, DateTimeKind.Local).AddTicks(2007),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 2,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 13, 21, 39, 37, 722, DateTimeKind.Local).AddTicks(2072),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaHoaDon = 3,
                            GhiChu = "",
                            MaKH = 1,
                            MaKM = "KM10",
                            MaNV = 1,
                            NgayLap = new DateTime(2026, 4, 13, 21, 39, 37, 722, DateTimeKind.Local).AddTicks(2109),
                            PhuongThucTT = "Tiền mặt",
                            SoLuongVe = 1,
                            SoTienGiam = 20000m,
                            TamTinh = 200000m,
                            TongTien = 180000m,
                            TrangThai = "Đã thanh toán"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKH");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.ToTable("KhachHang", t =>
                        {
                            t.HasCheckConstraint("CK_KH_Email_Format", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_KH_Sdt_Format", "LEN([Sdt]) >= 10 AND [Sdt] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            Email = "khach.tran@gmail.com",
                            HoTen = "Trần Thị Khách",
                            MaTK = "a72122c2-1421-4b9a-9759-ca33578591ce",
                            NgaySinh = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0912345678"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<double>("PhanTramGiam")
                        .HasColumnType("float");

                    b.Property<decimal>("SoTienToiDaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMai", t =>
                        {
                            t.HasCheckConstraint("CK_KM_PhanTram", "[PhanTramGiam] >= 0 AND [PhanTramGiam] <= 100");

                            t.HasCheckConstraint("CK_KM_SoTienToiDa", "[SoTienToiDaGiam] >= 0");

                            t.HasCheckConstraint("CK_KM_ThoiGian", "[NgayKetThuc] > [NgayBatDau]");
                        });

                    b.HasData(
                        new
                        {
                            MaKM = "KM10",
                            HinhAnh = "khai-truong.jpg",
                            MoTa = "Chào mừng hệ thống WebAppBookingBoat đi vào hoạt động. Giảm ngay 10% cho tất cả các tuyến tàu cao tốc.",
                            NgayBatDau = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 10.0,
                            SoTienToiDaGiam = 50000m,
                            TenChuongTrinh = "Giảm giá khai trương",
                            TrangThai = "Chưa diễn ra"
                        },
                        new
                        {
                            MaKM = "SUMMER26",
                            HinhAnh = "summer-sale.jpg",
                            MoTa = "Tận hưởng kỳ nghỉ hè tại Phú Quốc và Vũng Tàu với ưu đãi cực khủng lên đến 15% khi đặt vé trước 7 ngày.",
                            NgayBatDau = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 15.0,
                            SoTienToiDaGiam = 100000m,
                            TenChuongTrinh = "Ưu đãi mùa hè rực rỡ",
                            TrangThai = "Chưa diễn ra"
                        },
                        new
                        {
                            MaKM = "TET2026",
                            HinhAnh = "tet-holiday.jpg",
                            MoTa = "Chương trình khuyến mãi đặc biệt dành cho khách hàng về quê ăn Tết hoặc du xuân cùng gia đình.",
                            NgayBatDau = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 20.0,
                            SoTienToiDaGiam = 200000m,
                            TenChuongTrinh = "Vui Tết sum vầy",
                            TrangThai = "Chưa diễn ra"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<decimal>("GiaVeCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaTau")
                        .HasColumnType("int");

                    b.Property<int>("MaTuyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGioCapBenDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGioKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGheTrong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("MaTuyen");

                    b.HasIndex("MaTau", "NgayGioKhoiHanh")
                        .IsUnique();

                    b.ToTable("LichTrinh", t =>
                        {
                            t.HasCheckConstraint("CK_LT_GheTrong", "[SoGheTrong] >= 0");

                            t.HasCheckConstraint("CK_LT_GiaVe", "[GiaVeCoBan] >= 0");

                            t.HasCheckConstraint("CK_LT_ThoiGian", "[NgayGioCapBenDuKien] > [NgayGioKhoiHanh]");
                        });

                    b.HasData(
                        new
                        {
                            MaLichTrinh = 1,
                            GiaVeCoBan = 200000m,
                            MaTau = 1,
                            MaTuyen = 1,
                            NgayGioCapBenDuKien = new DateTime(2026, 4, 14, 10, 30, 0, 0, DateTimeKind.Local),
                            NgayGioKhoiHanh = new DateTime(2026, 4, 14, 8, 0, 0, 0, DateTimeKind.Local),
                            SoGheTrong = 20,
                            TrangThai = "Sắp khởi hành"
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Log", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("BangTacDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiLog")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaTK");

                    b.ToTable("Logs", t =>
                        {
                            t.HasCheckConstraint("CK_Log_Loai", "[LoaiLog] IN ('Info', 'Warning', 'Error', 'Critical')");
                        });

                    b.HasData(
                        new
                        {
                            MaLog = 1,
                            BangTacDong = "System",
                            HanhDong = "Khởi tạo hệ thống",
                            IpAddress = "127.0.0.1",
                            LoaiLog = "Info",
                            MaTK = "8b723ad0-b8ec-4a0f-80fe-651b03e1a53b",
                            NoiDungChiTiet = "Hệ thống đã khởi tạo dữ liệu mẫu (Seed Data) thành công.",
                            ThoiGian = new DateTime(2026, 4, 13, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLog = 2,
                            BangTacDong = "AspNetUsers",
                            HanhDong = "Cấu hình bảo mật",
                            IpAddress = "127.0.0.1",
                            LoaiLog = "Info",
                            MaTK = "8b723ad0-b8ec-4a0f-80fe-651b03e1a53b",
                            NoiDungChiTiet = "Thiết lập quyền Quản trị viên (Admin) cho hệ thống.",
                            ThoiGian = new DateTime(2026, 4, 13, 9, 0, 5, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaTK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNV");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.ToTable("NhanVien", t =>
                        {
                            t.HasCheckConstraint("CK_NV_Email_Format", "[Email] LIKE '%_@_%._%'");

                            t.HasCheckConstraint("CK_NV_Sdt_Format", "LEN([Sdt]) >= 10 AND [Sdt] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            ChucVu = "Bán vé",
                            Email = "chay.nv@boat.com",
                            HoTen = "Nguyễn Văn Chạy",
                            Luong = 0m,
                            MaTK = "8b723ad0-b8ec-4a0f-80fe-651b03e1a53b",
                            Sdt = "0987654321",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Tau", b =>
                {
                    b.Property<int>("MaTau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTau"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTau");

                    b.HasIndex("TenTau")
                        .IsUnique();

                    b.ToTable("Tau");

                    b.HasData(
                        new
                        {
                            MaTau = 1,
                            HinhAnh = "0ed53f9a-2e39-46ab-897c-856e7cde576d.jpg",
                            TenTau = "Tàu Cao Tốc 01",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 2,
                            HinhAnh = "2073e0cb-cf50-45b1-aa5e-9d40af4b7477.jpg",
                            TenTau = "Tàu Express 01",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 3,
                            HinhAnh = "872b8a7a-79ae-4f8b-96da-53c7e3caa5e3.jpg",
                            TenTau = "Tàu Cao Tốc 02",
                            TongSoGhe = 20,
                            TrangThai = true
                        },
                        new
                        {
                            MaTau = 4,
                            HinhAnh = "d0c7cc56-fd6c-4750-8095-2c250c2c3eed.jpg",
                            TenTau = "Tàu Express 02",
                            TongSoGhe = 20,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.TuyenDuong", b =>
                {
                    b.Property<int>("MaTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuyen"));

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("KhoangCach")
                        .HasColumnType("float");

                    b.Property<string>("TenTuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("ThoiGianDuKien")
                        .HasColumnType("time");

                    b.HasKey("MaTuyen");

                    b.HasIndex("DiemDi", "DiemDen")
                        .IsUnique();

                    b.ToTable("TuyenDuong");

                    b.HasData(
                        new
                        {
                            MaTuyen = 1,
                            DiemDen = "Vũng Tàu",
                            DiemDi = "Sài Gòn",
                            HinhAnh = "80eec6b7-1650-400a-afda-eec7573a7f48.jfif",
                            KhoangCach = 100.0,
                            TenTuyen = "Sài Gòn - Vũng Tàu",
                            ThoiGianDuKien = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            MaTuyen = 2,
                            DiemDen = "Phú Quốc",
                            DiemDi = "Rạch Giá",
                            HinhAnh = "dcc6e003-7560-4d50-8933-98682d3da2ef.jfif",
                            KhoangCach = 120.0,
                            TenTuyen = "Rạch Giá - Phú Quốc",
                            ThoiGianDuKien = new TimeSpan(0, 2, 45, 0, 0)
                        });
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<int?>("DanhGiaMaDanhGia")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVe");

                    b.HasIndex("DanhGiaMaDanhGia");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaLichTrinh", "MaGhe")
                        .IsUnique();

                    b.ToTable("Ve");

                    b.HasData(
                        new
                        {
                            MaVe = 1,
                            GiaVe = 180000m,
                            MaGhe = 2,
                            MaHoaDon = 1,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 2,
                            GiaVe = 180000m,
                            MaGhe = 3,
                            MaHoaDon = 2,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        },
                        new
                        {
                            MaVe = 3,
                            GiaVe = 180000m,
                            MaGhe = 4,
                            MaHoaDon = 3,
                            MaLichTrinh = 1,
                            TrangThai = "Hợp lệ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.DanhGia", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.LichTrinh", null)
                        .WithMany("DanhGias")
                        .HasForeignKey("LichTrinhMaLichTrinh")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Tau", "Tau")
                        .WithMany("Ghes")
                        .HasForeignKey("MaTau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tau");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.Tau", "Tau")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.TuyenDuong", "TuyenDuong")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tau");

                    b.Navigation("TuyenDuong");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Log", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ve", b =>
                {
                    b.HasOne("WebAppBookingBoat.Models.DanhGia", "DanhGia")
                        .WithMany()
                        .HasForeignKey("DanhGiaMaDanhGia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppBookingBoat.Models.Ghe", "Ghe")
                        .WithMany("Ves")
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.HoaDon", "HoaDon")
                        .WithMany("Ves")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppBookingBoat.Models.LichTrinh", "LichTrinh")
                        .WithMany("Ves")
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("Ghe");

                    b.Navigation("HoaDon");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Ghe", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.HoaDon", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.LichTrinh", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.Tau", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("LichTrinhs");
                });

            modelBuilder.Entity("WebAppBookingBoat.Models.TuyenDuong", b =>
                {
                    b.Navigation("LichTrinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
